name: java-retval
on: [push, pull_request]
jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Library
        run: ./gradlew clean build

      - name: assemble code-coverage report
        run: "mkdir -p bulid/distributions && ( cd build/reports/jacoco/test/html && zip -9r ../../../../distributions/jacoco-report.zip * )"
      - name: upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report.zip
          path: build/distributions/jacoco-report.zip
          retention-days: 5
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: retval.jar
          path: build/libs/retval-*.jar
          retention-days: 5
